# Generated by Django 6.1.1 on 2026-10-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('instructor', models.CharField(max_length=20)),
                ('fee', models.IntegerField()),
                ('duration', models.CharField(max_length=20)),
                ('mode', models.CharField(choices=[('offline', 'OFFLINE'), ('onine', 'ONLINE')], max_length=20)),
            ],
        ),
    ]
